modLoader = "javafml"
loaderVersion = "[32,)"
license = "MIT"

[[mods]]
    modId = "shifted_lens"
    version = "${file.jarVersion}"
    logoFile = "shifted_lens.png"
    authors = ".magmastrider., -Ghoul-, platypushasnohat"
    displayName = "Shifted Lens"
    description = '''Reworks vanilla hostile mobs with new animations, models, textures, and behaviors!'''

[[dependencies.shifted_lens]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.shifted_lens]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.3,)"
    ordering = "AFTER"
    side = "BOTH"